# Auto-assign configuration
addReviewers: true
addAssignees: author

# Review assignment
numberOfReviewers: 1
reviewers:
  - jcrouseilles

# Skip if already assigned
skipKeywords:
  - wip
  - WIP
  - draft
